name: Premake on multiple platforms

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop"]

jobs:
  build_windows:
    runs-on: windows-latest
    env:
      SOLUTION_FILE_PATH: .
      BUILD_CONFIGURATION: Release
    steps:
      - uses: actions/checkout@v4

      - name: Checkout FlightKit
        uses: actions/checkout@v4
        with:
          repository: kietran99/FlightKitCpp
          path: FlightKitCpp

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          $PremakePath = & python "FlightKitCpp\Premake\get_binaries.py"
          if (-not $PremakePath) {
              Write-Error "Failed to get Premake path from get_binaries.py"
              exit 1
          }
          & "$PremakePath" --file=Build.lua vs2022
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

      - name: Test
        working-directory: Binaries\windows-x86_64\${{env.BUILD_CONFIGURATION}}\Tests
        run: .\Tests.exe
